services:
  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: techzu-redis-dev
    ports:
      - "6379:6379"
    restart: always
  # MongoDB Service (Optional if using cloud/local DB)
  # mongodb:
  #   image: mongo:latest
  #   container_name: techzu-mongodb-dev
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_dev_data:/data/db
  #   restart: always

  # volumes:
  #   mongodb_dev_data:
